# Generated by Django 3.2.8 on 2021-10-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('cellphone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
