# Generated by Django 3.2.8 on 2021-10-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='passenger',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
