# Generated by Django 3.2.7 on 2021-10-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='date_travel',
            field=models.DateTimeField(),
        ),
    ]
