# Generated by Django 3.2.7 on 2021-11-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_alter_travel_date_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
