# Generated by Django 3.2.7 on 2021-11-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_travel_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
